# Explore here

In [1]:
#pip install xlrd
import pandas as pd
import xlrd

df = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/4923045/8288208/pokemon_data.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240530%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240530T211005Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=4cede0a78d710cbd627b23e8dc2d09ff78a9adc95d9b66dcb90d9d6a7e76902241f6d654df8e97ced5278c9b244d711e906a4d0adf145483e516fc5dfc2ed69fedaf2aeb4f1db5b5765f2de2372cf02c2da9cf00aa572bc42e6c258a2413c322ea87ea9b0ddc533ddbd26a9d72433c57928616a09bb01b818cac771b028a81cc62437c30ef0e24d4b91594b4178ce51e97bb6906843a0f0dc0a34e856e74757c5f432600c4b543a76f0164cffbe2306dc0bef87fbc782b6f1e9f6beebb9419b62be7a90bc78fe3f3a2a0253a433c063d486d9f56d6e02b5ff8ed27c5fea1b00605946105c95428832a608be2d4077a5ae5aa3ca7a78a86a560b1be6612f22fa3')
df.to_csv('../data/raw/pokemon_data_raw.csv', index=False)
df

,dexnum,name,generation,type1,type2,species,height,weight,ability1,ability2,...,catch_rate,base_friendship,base_exp,growth_rate,egg_group1,egg_group2,percent_male,percent_female,egg_cycles,special_group
0,1,Bulbasaur,1,Grass,Poison,Seed Pokémon,0.7,6.9,Overgrow,Chlorophyll,...,45,50,64,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
1,2,Ivysaur,1,Grass,Poison,Seed Pokémon,1.0,13.0,Overgrow,Chlorophyll,...,45,50,142,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
2,3,Venusaur,1,Grass,Poison,Seed Pokémon,2.0,100.0,Overgrow,Chlorophyll,...,45,50,236,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
3,4,Charmander,1,Fire,NaN,Lizard Pokémon,0.6,8.5,Blaze,Solar Power,...,45,50,62,Medium Slow,Dragon,Monster,87.5,12.5,20,Ordinary
4,5,Charmeleon,1,Fire,NaN,Flame Pokémon,1.1,19.0,Blaze,Solar Power,...,45,50,142,Medium Slow,Dragon,Monster,87.5,12.5,20,Ordinary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,Raging Bolt,9,Electric,Dragon,Paradox Pokémon,5.2,480.0,Protosynthesis,NaN,...,10,—,—,Slow,Undiscovered,NaN,NaN,NaN,—,Ancient Paradox
1021,1022,Iron Boulder,9,Rock,Psychic,Paradox Pokémon,1.5,162.5,Quark Drive,NaN,...,10,—,—,Slow,Undiscovered,NaN,NaN,NaN,—,Future Paradox
1022,1023,Iron Crown,9,Steel,Psychic,Paradox Pokémon,1.6,156.0,Quark Drive,NaN,...,10,—,—,Slow,Undiscovered,NaN,NaN,NaN,—,Future Paradox
1023,1024,Terapagos,9,Normal,NaN,Tera Pokémon,0.2,6.5,Tera Shift,NaN,...,255,—,—,Slow,Undiscovered,NaN,50.0,50.0,—,Legendary
1024,1025,Pecharunt,9,Poison,Ghost,Subjugation Pokémon,0.3,0.3,Poison Puppeteer,NaN,...,3,—,—,Slow,Undiscovered,NaN,NaN,NaN,—,Mythical

In [2]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   dexnum           1025 non-null   int64
 1   name             1025 non-null   object
 2   generation       1025 non-null   int64
 3   type1            1025 non-null   object
 4   type2            526 non-null    object
 5   species          1025 non-null   object
 6   height           1025 non-null   float64
 7   weight           1025 non-null   float64
 8   ability1         1025 non-null   object
 9   ability2         858 non-null    object
 10  hidden_ability   530 non-null    object
 11  hp               1025 non-null   int64
 12  attack           1025 non-null   int64
 13  defense          1025 non-null   int64
 14  sp_atk           1025 non-null   int64
 15  sp_def           1025 non-null   int64
 16  speed            1025 non-null   int64
 17  total            1025 non-null   int64
 18  ev_yield         1025 non-null   object
 19  catch_rate       1025 non-null   int64
 20  base_friendship  1025 non-null   object
 21  base_exp         1025 non-null   object
 22  growth_rate      1025 non-null   object
 23  egg_group1       1025 non-null   object
 24  egg_group2       279 non-null    object
 25  percent_male     870 non-null    float64
 26  percent_female   870 non-null    float64
 27  egg_cycles       1025 non-null   object
 28  special_group    1025 non-null   object
dtypes: float64(4), int64(10), object(15)
memory usage: 232.4+ KB

,dexnum,generation,height,weight,hp,attack,defense,sp_atk,sp_def,speed,total,catch_rate,percent_male,percent_female
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,870.000000,870.000000
mean,513.000000,4.741463,1.211610,66.981659,70.184390,77.521951,72.507317,70.080976,70.205854,67.186341,427.686829,94.927805,54.928161,45.071839
std,296.036315,2.633633,1.248167,121.275372,26.631054,29.782541,29.286972,29.658378,26.639329,28.717227,112.770735,76.108415,20.308375,20.308375
min,1.000000,1.000000,0.100000,0.100000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000,3.000000,0.000000,0.000000
25%,257.000000,3.000000,0.500000,8.500000,50.000000,55.000000,50.000000,47.000000,50.000000,45.000000,325.000000,45.000000,50.000000,50.000000
50%,513.000000,5.000000,1.000000,28.000000,68.000000,75.000000,70.000000,65.000000,67.000000,65.000000,450.000000,60.000000,50.000000,50.000000
75%,769.000000,7.000000,1.500000,70.000000,85.000000,100.000000,90.000000,90.000000,86.000000,88.000000,508.000000,140.000000,50.000000,50.000000
max,1025.000000,9.000000,20.000000,999.900000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000,720.000000,255.000000,100.000000,100.000000

In [3]:
df.columns

Index(['dexnum', 'name', 'generation', 'type1', 'type2', 'species', 'height',
       'weight', 'ability1', 'ability2', 'hidden_ability', 'hp', 'attack',
       'defense', 'sp_atk', 'sp_def', 'speed', 'total', 'ev_yield',
       'catch_rate', 'base_friendship', 'base_exp', 'growth_rate',
       'egg_group1', 'egg_group2', 'percent_male', 'percent_female',
       'egg_cycles', 'special_group'],
      dtype='object')

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Usar la suma de las caracteristicas ('total') para predecir la tasa de crecimiento ('growth_rate')
caracteristicas = df[['total']]
pokeresultado = df['growth_rate']

X_train, X_test, y_train, y_test = train_test_split(caracteristicas, pokeresultado, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelo_regrlog = LogisticRegression(max_iter=1000)

modelo_regrlog.fit(X_train_scaler, y_train)

y_pred = modelo_regrlog.predict(X_test_scaler)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.4975609756097561

In [6]:
from sklearn.tree import DecisionTreeClassifier

modelo_arbol = DecisionTreeClassifier(random_state=42)

modelo_arbol.fit(X_train, y_train)

y_pred = modelo_arbol.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.5024390243902439

In [7]:
from sklearn.ensemble import RandomForestClassifier

modelo_bosque = RandomForestClassifier(n_estimators=100, random_state=42)

modelo_bosque.fit(X_train, y_train)

y_pred = modelo_bosque.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
#Seleccionado para mejorar hiperparametros

Accuracy: 0.526829268292683

In [8]:
from sklearn.ensemble import GradientBoostingClassifier

modelo_boosting = GradientBoostingClassifier(random_state=42)

modelo_boosting.fit(X_train, y_train)

y_pred = modelo_boosting.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.4975609756097561

In [9]:
from sklearn.naive_bayes import GaussianNB

modelo_naive = GaussianNB()

modelo_naive.fit(X_train, y_train)

y_pred = modelo_naive.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.5121951219512195

In [10]:
from sklearn.neighbors import KNeighborsClassifier

modelo_vecinos = KNeighborsClassifier(n_neighbors=5)

modelo_vecinos.fit(X_train, y_train)

y_pred = modelo_vecinos.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.4878048780487805

In [22]:
#Guardado del modelo Random Forest ('modelo_bosque')
from pickle import dump

dump(modelo_bosque, open("../models/random_forest_classifier_default_42.sav", "wb"))

In [25]:
import sklearn
print(sklearn.__version__)

1.5.0